### PR TITLE
fix(platform-server): delete relevant files in storage when property is deleted

### LINKED ISSUE #108: delete relevant files in storage when page is deleted

### PR DESCRIPTION
**Pull request by lizimeow**
close #108

### CODE REVIEW

File: packages/platform-server/src/modules/snapshot/snapshot-report/service.ts [hunk 1]
```diff
@@ -169,20 +172,29 @@ export class SnapshotReportService {
...
+          report.traceEventsStorageKey,
+          report.flameChartStorageKey,
+          report.sourceCoverageStorageKey,
+        )
+
+        return report.id
+      })
+      await this.storage.bulkDelete(storageKeys.filter(Boolean) as string[])
+      await SnapshotReport.delete(ids)
+      await SourceIssue.delete({ snapshotReportId: In(ids) })
```
Comment (forehalo) [inline packages/platform-server/src/modules/snapshot/snapshot-report/service.ts:197]: delete by foreign key constraint

**Review by forehalo — APPROVED** [review]
